-- ============================================================================
--  multiai.online — schema
--  Run in pgAdmin against the "multiai" database (Query Tool → open → Execute).
--  Idempotent: safe to run twice, creates nothing that already exists.
-- ============================================================================
--
--  If the database and role do not exist yet, run these two lines FIRST while
--  connected to "postgres", then reconnect to "multiai" and run the rest:
--
--      CREATE ROLE multiai WITH LOGIN PASSWORD 'change-this-password';
--      CREATE DATABASE multiai WITH OWNER multiai ENCODING 'UTF8';
--
--  CREATE DATABASE cannot run inside a transaction block, so pgAdmin will
--  refuse it if it is bundled with the statements below.
-- ============================================================================

BEGIN;

SET client_min_messages = warning;

-- Timestamps are stored naive UTC to match the Python layer (datetime.utcnow).
CREATE OR REPLACE FUNCTION utcnow() RETURNS timestamp
    LANGUAGE sql STABLE AS $$ SELECT (now() AT TIME ZONE 'utc') $$;


-- ---------------------------------------------------------------- users ----
CREATE TABLE IF NOT EXISTS users (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(255) NOT NULL,
    display_name  varchar(80)  NOT NULL DEFAULT '',
    -- Null for accounts that only ever signed in with Google.
    password_hash varchar(255),
    google_sub    varchar(64),
    avatar_url    varchar(512) NOT NULL DEFAULT '',
    last_login_at timestamp,
    created_at    timestamp    NOT NULL DEFAULT utcnow(),
    CONSTRAINT uq_users_email      UNIQUE (email),
    CONSTRAINT uq_users_google_sub UNIQUE (google_sub),
    CONSTRAINT ck_users_login_method
        CHECK (password_hash IS NOT NULL OR google_sub IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);
CREATE INDEX IF NOT EXISTS ix_users_google_sub ON users (google_sub)
    WHERE google_sub IS NOT NULL;

COMMENT ON TABLE users IS 'Account holders. Passwords are werkzeug pbkdf2 hashes.';
COMMENT ON COLUMN users.google_sub IS 'Google''s stable account id (the "sub" claim).';


-- ---------------------------------------------------------- credentials ----
-- Provider API keys. key_encrypted holds a Fernet token, never plaintext.
CREATE TABLE IF NOT EXISTS credentials (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer      NOT NULL,
    provider      varchar(32)  NOT NULL,
    label         varchar(80)  NOT NULL,
    key_encrypted text         NOT NULL,
    key_hint      varchar(64)  NOT NULL DEFAULT '',
    base_url      varchar(255),
    created_at    timestamp    NOT NULL DEFAULT utcnow(),
    CONSTRAINT fk_credentials_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_credentials_provider
        CHECK (provider IN ('anthropic', 'openai', 'gemini', 'custom'))
);

CREATE INDEX IF NOT EXISTS ix_credentials_user ON credentials (user_id);

COMMENT ON COLUMN credentials.key_encrypted IS
    'Fernet token. Decryptable only with security.encryption_key from config.json.';
COMMENT ON COLUMN credentials.base_url IS
    'Only for provider = custom: any OpenAI-compatible endpoint.';


-- --------------------------------------------------------------- agents ----
CREATE TABLE IF NOT EXISTS agents (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer          NOT NULL,
    credential_id integer,
    name          varchar(60)      NOT NULL,
    provider      varchar(32)      NOT NULL,
    model         varchar(120)     NOT NULL,
    role          varchar(120)     NOT NULL DEFAULT '',
    system_prompt text             NOT NULL DEFAULT '',
    temperature   double precision NOT NULL DEFAULT 0.7,
    max_tokens    integer          NOT NULL DEFAULT 1200,
    color         varchar(16)      NOT NULL DEFAULT '#2F2BA8',
    archived      boolean          NOT NULL DEFAULT false,
    created_at    timestamp        NOT NULL DEFAULT utcnow(),
    CONSTRAINT fk_agents_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_agents_credential
        FOREIGN KEY (credential_id) REFERENCES credentials (id) ON DELETE SET NULL,
    CONSTRAINT ck_agents_provider
        CHECK (provider IN ('anthropic', 'openai', 'gemini', 'custom')),
    CONSTRAINT ck_agents_temperature CHECK (temperature >= 0 AND temperature <= 2),
    CONSTRAINT ck_agents_max_tokens  CHECK (max_tokens BETWEEN 100 AND 32000)
);

CREATE INDEX IF NOT EXISTS ix_agents_user ON agents (user_id) WHERE archived = false;

COMMENT ON COLUMN agents.name IS
    'How other models address this agent inside the transcript.';
COMMENT ON COLUMN agents.credential_id IS
    'NULL means fall back to the server-wide key in config.json, if set.';


-- --------------------------------------------------------------- groups ----
-- "groups" is a non-reserved keyword in Postgres, so it needs no quoting,
-- but it is quoted here so the DDL survives being pasted into other tools.
CREATE TABLE IF NOT EXISTS "groups" (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              integer      NOT NULL,
    name                 varchar(120) NOT NULL,
    purpose              text         NOT NULL DEFAULT '',
    rounds               integer      NOT NULL DEFAULT 2,
    synthesizer_agent_id integer,
    created_at           timestamp    NOT NULL DEFAULT utcnow(),
    CONSTRAINT fk_groups_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_groups_synthesizer
        FOREIGN KEY (synthesizer_agent_id) REFERENCES agents (id) ON DELETE SET NULL,
    CONSTRAINT ck_groups_rounds CHECK (rounds BETWEEN 1 AND 10)
);

CREATE INDEX IF NOT EXISTS ix_groups_user ON "groups" (user_id);

COMMENT ON COLUMN "groups".synthesizer_agent_id IS
    'The chair: reads the whole transcript and writes the verdict. NULL = seat 1.';


-- -------------------------------------------------------- group_members ----
CREATE TABLE IF NOT EXISTS group_members (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL,
    agent_id integer NOT NULL,
    seat     integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_group_members_group
        FOREIGN KEY (group_id) REFERENCES "groups" (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_members_agent
        FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE,
    CONSTRAINT uq_group_agent UNIQUE (group_id, agent_id)
);

CREATE INDEX IF NOT EXISTS ix_group_members_group ON group_members (group_id, seat);
CREATE INDEX IF NOT EXISTS ix_group_members_agent ON group_members (agent_id);

COMMENT ON COLUMN group_members.seat IS
    'Speaking order. Seat 1 opens each round; later seats read the turns already taken.';


-- ---------------------------------------------------------- discussions ----
CREATE TABLE IF NOT EXISTS discussions (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id         integer     NOT NULL,
    question         text        NOT NULL,
    rounds           integer     NOT NULL DEFAULT 1,
    mode             varchar(8)  NOT NULL DEFAULT 'step',
    status           varchar(16) NOT NULL DEFAULT 'queued',
    stage            varchar(160) NOT NULL DEFAULT 'Waiting for you',
    error            text,
    cancel_requested boolean     NOT NULL DEFAULT false,
    created_at       timestamp   NOT NULL DEFAULT utcnow(),
    finished_at      timestamp,
    CONSTRAINT fk_discussions_group
        FOREIGN KEY (group_id) REFERENCES "groups" (id) ON DELETE CASCADE,
    CONSTRAINT ck_discussions_status
        CHECK (status IN ('queued', 'running', 'idle', 'done', 'failed', 'cancelled')),
    CONSTRAINT ck_discussions_mode CHECK (mode IN ('step', 'flow'))
);

CREATE INDEX IF NOT EXISTS ix_discussions_group  ON discussions (group_id, id DESC);
CREATE INDEX IF NOT EXISTS ix_discussions_status ON discussions (status)
    WHERE status IN ('queued', 'running');

COMMENT ON COLUMN discussions.stage IS
    'Human-readable progress line polled by the browser, e.g. "Round 2: Ada is thinking".';


-- ------------------------------------------------------------- messages ----
-- One turn each. Rows here are re-read and fed into the next model's prompt,
-- which is what makes the panel a conversation rather than parallel answers.
CREATE TABLE IF NOT EXISTS messages (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discussion_id integer      NOT NULL,
    agent_id      integer,
    role          varchar(16)  NOT NULL DEFAULT 'turn',
    round_no      integer      NOT NULL DEFAULT 0,
    seat          integer      NOT NULL DEFAULT 0,
    speaker       varchar(60)  NOT NULL DEFAULT 'You',
    provider      varchar(32)  NOT NULL DEFAULT '',
    model         varchar(120) NOT NULL DEFAULT '',
    color         varchar(16)  NOT NULL DEFAULT '#172033',
    content       text         NOT NULL DEFAULT '',
    latency_ms    integer,
    input_chars   integer,
    created_at    timestamp    NOT NULL DEFAULT utcnow(),
    CONSTRAINT fk_messages_discussion
        FOREIGN KEY (discussion_id) REFERENCES discussions (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_agent
        FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL,
    CONSTRAINT ck_messages_role
        CHECK (role IN ('question', 'turn', 'verdict', 'error', 'note'))
);

-- The hot path: "give me every turn in this discussion after id N", called
-- once per SSE poll and once before every model call.
CREATE INDEX IF NOT EXISTS ix_messages_discussion_id ON messages (discussion_id, id);

COMMENT ON COLUMN messages.input_chars IS
    'Size of the transcript this speaker was given — how much of the others it read.';


-- ------------------------------------------------------------- version ----
CREATE TABLE IF NOT EXISTS schema_version (
    version    integer   NOT NULL PRIMARY KEY,
    applied_at timestamp NOT NULL DEFAULT utcnow(),
    note       text      NOT NULL DEFAULT ''
);

INSERT INTO schema_version (version, note)
VALUES (1, 'initial schema')
ON CONFLICT (version) DO NOTHING;


-- -------------------------------------------------------------- grants ----
-- Adjust the role name if your login role is not "multiai".
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'multiai') THEN
        EXECUTE 'GRANT USAGE ON SCHEMA public TO multiai';
        EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO multiai';
        EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO multiai';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public
                 GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO multiai';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public
                 GRANT USAGE, SELECT ON SEQUENCES TO multiai';
    END IF;
END
$$;

COMMIT;

-- ============================================================================
--  Checks after running
-- ============================================================================
-- SELECT table_name FROM information_schema.tables
--  WHERE table_schema = 'public' ORDER BY table_name;
--
-- Expected: agents, credentials, discussions, group_members, groups,
--           messages, schema_version, users
