-- ============================================================================
--  multiai.online — migration 004: shared files
--  Run in pgAdmin against the "multiai" database, after 003_rooms.sql.
--  Idempotent: safe to run twice.
-- ============================================================================
--
--  Files you upload into a topic. The extracted text is what the agents read;
--  the original bytes stay on disk so you can download them again.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS attachments (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discussion_id integer      NOT NULL,
    user_id       integer      NOT NULL,
    filename      varchar(255) NOT NULL,
    mime          varchar(120) NOT NULL DEFAULT '',
    size_bytes    integer      NOT NULL DEFAULT 0,
    stored_path   varchar(512) NOT NULL DEFAULT '',
    extracted     text         NOT NULL DEFAULT '',
    extract_chars integer      NOT NULL DEFAULT 0,
    truncated     boolean      NOT NULL DEFAULT false,
    note          varchar(255) NOT NULL DEFAULT '',
    created_at    timestamp    NOT NULL DEFAULT utcnow(),
    CONSTRAINT fk_attachments_discussion
        FOREIGN KEY (discussion_id) REFERENCES discussions (id) ON DELETE CASCADE,
    CONSTRAINT fk_attachments_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_attachments_discussion
    ON attachments (discussion_id, id);

COMMENT ON COLUMN attachments.extracted IS
    'Plain text handed to every agent. Empty for files we cannot read.';
COMMENT ON COLUMN attachments.note IS
    'Why a file could not be read, shown to the user and to the agents.';
COMMENT ON COLUMN attachments.stored_path IS
    'Path on disk under storage.upload_dir. Empty if the file was not kept.';

INSERT INTO schema_version (version, note)
VALUES (4, 'file attachments')
ON CONFLICT (version) DO NOTHING;

COMMIT;
